typography_spectrum: 0.5354056181386113
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.5575496419332922
  lightness: 0.09403638145886362
  saturation: 0.26804247917607427
  rhythmicContrast: 0.846022178651765
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6678409248124808
analytics:
  google: null
  facebook: null
  twitter: null
name: Triebwerken
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Us
    id: ea76b980-a500-4ef0-9a1c-d93d2dbd71fb
    type: content
favicon: null
title: Power the Future
purpose: []
